channels:
- bioconda
- conda-forge
- defaults
dependencies:
- python=3.10
- pip
- abricate
- prokka
- mlst
- ncbi-amrfinderplus
- iqtree
- trimmomatic
- bwa
- samtools
- bcftools
- perl=5.32
- perl-bioperl
- perl-app-cpanminus
- libgfortran5
- openjdk=17
- numpy
- pandas
- matplotlib
- biopython
name: rmap-1.0
